def getVarNames():
    VarNames = {'axav' : 0,
                        'axmn' : 0,
                        'axmx' : 0,
                        'ayav' : 0,
                        'aymn' : 0,
                        'aymx' : 0,
                        'azav' : 0,
                        'azmn' : 0,
                        'azmx' : 0,
                        'gxav' : 0,
                        'gxmn' : 0,
                        'gxmx' : 0,
                        'gyav' : 0,
                        'gymn' : 0,
                        'gymx' : 0,
                        'gzav' : 0,
                        'gzmn' : 0,
                        'gzmx' : 0,
                        'mxav' : 0,
                        'mxmn' : 0,
                        'mxmn' : 0,
                        'mxmx' : 0,
                        'myav' : 0,
                        'mymn' : 0,
                        'mymx' : 0,
                        'mzav' : 0,
                        'mzmn' : 0,
                        'mzmx' : 0,
                        'btmp' : 0,
                        'bite' : 0,
                        'bvol' : 0,
                        'time' : 0,
                        'imei' : 0}
    return VarNames                    